BoxLayout:
    orientation: 'vertical'

    Label:
        text: app.status_text
        font_size: 60
        size_hint_y: 0.2

    BoxLayout:
        orientation: 'horizontal'

        Button:
            text: "Increase"
            on_press: app.handle_press(1)

        Button:
            text: "Decrease"
            on_press: app.handle_press(-1)

    BoxLayout:
        id: container_box

    Label:
        text: "Success!"
        size_hint_y: 0.1
